# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaExamen',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Examen',
                'proxy': True,
            },
            bases=('preguntas.pregunta',),
        ),
    ]
