# Generated by Django 2.1 on 2018-08-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0002_preguntaexamen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.TextField(verbose_name='Pregunta')),
            ],
            options={
                'ordering': ['Descripcion'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='materia',
            unique_together={('Descripcion',)},
        ),
    ]
