# Generated by Django 2.1 on 2018-08-02 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0003_auto_20180802_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='materia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='preguntas.Materia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materia',
            name='Descripcion',
            field=models.TextField(verbose_name='Materia'),
        ),
    ]
