# Generated by Django 2.1.7 on 2019-02-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0004_auto_20180802_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='posibilidad',
            field=models.IntegerField(default=20),
        ),
    ]
