# Generated by Django 2.1.7 on 2019-07-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0006_auto_20190219_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='nivel',
            field=models.CharField(choices=[('FACIL', 'Facil'), ('INTERMEDIO', 'Intermedio'), ('DIFICIL', 'Dificil')], default='INTERMEDIO', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='posibilidad',
            field=models.IntegerField(default=50),
        ),
    ]
