# Generated by Django 2.1.7 on 2019-08-03 03:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0007_auto_20190715_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='Descripcion',
            field=ckeditor.fields.RichTextField(verbose_name='Pregunta'),
        ),
    ]
