# Generated by Django 2.1.7 on 2020-05-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0008_auto_20190803_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='tags',
            field=models.ManyToManyField(blank=True, to='preguntas.Tag'),
        ),
    ]
